export default {
	CENTRAL_PROCESSING_UNIT: 'CENTRAL_PROCESSING_UNIT',
	MOTHERBOARD: 'MOTHERBOARD',
	RANDOM_ACCESS_MEMORY: 'RANDOM_ACCESS_MEMORY',
	SOLID_STATE_DRIVE: 'SOLID_STATE_DRIVE',
	GRAPHICS_PROCESSING_UNIT: 'GRAPHICS_PROCESSING_UNIT',
	DISPLAY: 'DISPLAY',
	SOUND: 'SOUND',
	KEYBOARD: 'KEYBOARD',
	MOUSE: 'MOUSE'
};